# Generated by Django 2.0.6 on 2020-10-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_usercourse_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
