# Generated by Django 2.0.6 on 2020-10-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='视频'),
        ),
    ]
